pub const ENV_VARIABLE__NEXTAUTH_SECRET: &str = "NEXTAUTH_SECRET";
pub const ENV_VARIABLE__ASYMMETRIC_ENCRYPTION_PUBLIC_KEY: &str = "ASYMMETRIC_ENCRYPTION_PUBLIC_KEY";
pub const ENV_VARIABLE__ASYMMETRIC_ENCRYPTION_PRIVATE_KEY: &str = "ASYMMETRIC_ENCRYPTION_PRIVATE_KEY";